base_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),
    path('users/', include('users.urls')),
    path('', include('quiz.urls')),
]

quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category_quizzes'),
    path('quiz/<int:pk>/', views.QuizView.as_view(), name='quiz_details'),
    path('quiz/<int:pk>/take/', views.TakeQuizView.as_view(), name='take_quiz'),
    path('result/<int:pk>/', views.ResultDetailsView.as_view(), name='result_details'),
    path('results/', views.UserResultsView.as_view(), name='results'),

    path('quizzes/change/', views.QuizListView.as_view(), name='quiz_change_list'),
    path('quiz/add/', views.QuizCreateView.as_view(), name='quiz_add'),
    path('quiz/<int:pk>/change/', views.QuizUpdateView.as_view(), name='quiz_change'),
    path('quiz/<int:pk>/delete/', views.QuizDeleteView.as_view(), name='quiz_delete'),

    path('categories/change/', views.CategoryListView.as_view(), name='category_change_list'),
    path('category/add/', views.CategoryCreateView.as_view(), name='category_add'),
    path('category/<int:pk>/change/', views.CategoryUpdateView.as_view(), name='category_change'),
    path('category/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('quiz/<int:pk>/question/add/', views.QuestionAddView.as_view(), name='question_add'),
    path('quiz/<int:quiz_pk>/question/<int:question_pk>/', views.question_change, name='question_change'),
    path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', views.QuestionDeleteView.as_view(), name='question_delete')
]

quiz/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        unique=True
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='created_categories'
    )
    description = models.TextField(max_length=500)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('quiz:category_quizzes', args=[str(self.id)])


class Quiz(models.Model):
    creator = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='created_quizzes'
    )
    created_on = models.DateTimeField(auto_now_add=True)
    subject = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='quizzes'
    )

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse('quiz:quiz_details', args=[str(self.id)])


class Question(models.Model):
    subject = models.CharField(max_length=100)
    body = models.TextField(max_length=1000)
    explanation = models.TextField(
        max_length=500,
        blank=True
    )
    question_type = models.CharField(
        max_length=1,
        choices=(
            ('R', 'Radio Button'),
            ('C', 'Checkbox'),
            ('T', 'Text field')
        ),
        default='R'
    )
    created_on = models.DateTimeField(auto_now_add=True)
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name='questions'
    )

    def __str__(self):
        return self.subject


class Choice(models.Model):
    body = models.TextField(max_length=500)
    created_on = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name='choices',
        null=True
    )
    correct = models.NullBooleanField()

    def __str__(self):
        return self.body


class TakenQuiz(models.Model):
    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='taken_quizzes'
    )
    created_on = models.DateTimeField(auto_now_add=True)
    time = models.DurationField(null=True)
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name='taken_quizzes'
    )
    score = models.FloatField(null=True)
    answers = models.TextField(blank=True)

    def __str__(self):
        return '{} taken by {} at {}, score: {}'.format(self.quiz, self.creator, self.created_on, self.score)

    def get_absolute_url(self):
        return reverse('quiz:result_details', args=[str(self.id)])

quiz/forms.py
from django import forms
from . import models
from django.core.exceptions import ValidationError


class BaseTakeQuizForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.question = question
        self.fields['answer'].queryset = question.choices.order_by('body')


class TakeQuizRadioForm(BaseTakeQuizForm):
    answer = forms.ModelChoiceField(
        queryset=models.Choice.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None,
        label='Варианты ответов'
    )


class TakeQuizMultiForm(BaseTakeQuizForm):
    answer = forms.ModelMultipleChoiceField(
        queryset=models.Choice.objects.none(),
        widget=forms.CheckboxSelectMultiple(),
        required=True,
        label='Варианты ответов'
    )


class TakeQuizTextForm(BaseTakeQuizForm):
    answer = forms.CharField(label='Введите ответ', widget=forms.Textarea(attrs={'cols': 20, 'rows': 2}))


class QuestionForm(forms.ModelForm):
    class Meta:
        model = models.Question
        fields = ('subject', 'body', 'explanation', 'question_type')


class BaseChoiceInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()
        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Отметьте хотя бы один верный ответ.', code='no_correct_answer')

quiz/views.py
from django.views import generic
from .models import Category, Quiz, Question, TakenQuiz, Choice
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.db.models import QuerySet, Count
from . import forms
from json import dumps, loads
from django.contrib import messages
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from users.decorators import moderator_required
from django.utils.decorators import method_decorator
from django.utils import timezone


class HomeView(generic.ListView):
    template_name = 'quiz/home.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.annotate(quizzes_count=Count('quizzes'))


class CategoryView(generic.ListView):
    template_name = 'quiz/category.html'
    context_object_name = 'quizzes'

    def get_category(self):
        return get_object_or_404(Category, pk=self.kwargs['pk'])

    def get_queryset(self):
        return self.get_category().quizzes.annotate(questions_count=Count('questions'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.get_category()
        return context


class QuizView(generic.DetailView):
    template_name = 'quiz/quiz.html'
    context_object_name = 'quiz'

    def get_queryset(self):
        return Quiz.objects.select_related('creator', 'category')\
            .filter(pk=self.kwargs['pk'])\
            .annotate(questions_count=Count('questions'))


class TakeQuizView(generic.FormView):
    template_name = 'quiz/take_quiz.html'
    http_method_names = ['post']

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        form = context_data['form']
        context_data.update({
            'question_num': self.request.session['quiz_data']['current_pos'] + 1,
            'questions_count': self.request.session['quiz_data']['total_questions'],
            'question': form.question,
            'quiz': form.question.quiz,
            'category': form.question.quiz.category,
        })
        return context_data

    def post(self, request, *args, **kwargs):
        quiz_data = request.session.get('quiz_data')
        if quiz_data:
            if quiz_data['quiz'] != kwargs['pk']:
                messages.error(request, 'Вы еще не завершили этот опрос.')
                return redirect('quiz:quiz_details', quiz_data['quiz'])
            form = self.get_form(data=request.POST)
            if form.is_valid():
                return self.form_valid(form)
            return self.form_invalid(form)
        return self.first_form(request, kwargs)

    def first_form(self, request, kwargs):
        quiz = get_object_or_404(Quiz, pk=kwargs['pk'])
        questions = list(quiz.questions.values_list('id', flat=True))
        taken_quiz = TakenQuiz.objects.create(
            creator=request.user,
            quiz=quiz
        )
        request.session['quiz_data'] = {
            'quiz': kwargs['pk'],
            'questions': questions,
            'current_pos': 0,
            'answers': {},
            'taken_quiz': taken_quiz.id,
            'total_questions': len(questions)
        }
        return self.render_to_response(self.get_context_data())

    def get_form(self, **kwargs):
        quiz_data = self.request.session['quiz_data']
        question = Question.objects \
            .select_related('quiz', 'quiz__category')\
            .get(pk=quiz_data['questions'][quiz_data['current_pos']])
        return {
            'R': forms.TakeQuizRadioForm,
            'C': forms.TakeQuizMultiForm,
            'T': forms.TakeQuizTextForm
        }[question.question_type](question, **kwargs)

    def form_valid(self, form):
        quiz_data = self.request.session['quiz_data']
        questions = quiz_data['questions']
        current_pos = quiz_data['current_pos']
        answer = form.cleaned_data['answer']
        if isinstance(answer, Choice):
            quiz_data['answers'][questions[current_pos]] = {'pk': form.cleaned_data['answer'].id}
        elif isinstance(answer, QuerySet):
            quiz_data['answers'][questions[current_pos]] = {'pks': list(form.cleaned_data['answer'].values_list('id', flat=True))}
        else:
            quiz_data['answers'][questions[current_pos]] = {'txt': form.cleaned_data['answer']}
        self.request.session['quiz_data']['answers'] = quiz_data['answers']
        if current_pos >= len(questions) - 1:
            score = self.calculate_results(quiz_data['answers'])
            taken_quiz = TakenQuiz.objects.select_related('quiz', 'quiz__category')\
                .get(id=quiz_data['taken_quiz'])
            taken_quiz.answers = dumps(quiz_data['answers'])
            taken_quiz.time = timezone.now() - taken_quiz.created_on
            taken_quiz.score = int(score)
            taken_quiz.save()
            del self.request.session['quiz_data']
            return render(self.request, 'quiz/finished_quiz.html', {
                'taken_quiz': taken_quiz,
                'category': taken_quiz.quiz.category,
                'quiz': taken_quiz.quiz
            })
        else:
            current_pos += 1
            quiz_data['current_pos'] = current_pos
            self.request.session['quiz_data'] = quiz_data
            return self.render_to_response(self.get_context_data())

    @staticmethod
    def calculate_results(answers):
        for question_pk, question_answers in answers.items():
            if 'pk' in question_answers:
                question_answers['correct'] = True if Choice.objects.get(pk=question_answers['pk']).correct is True else False
            elif 'pks' in question_answers:
                correct_answers = set(Question.objects.get(pk=question_pk).choices.filter(correct=True).values_list('id', flat=True))
                given_answers = set(question_answers['pks'])
                question_answers['correct'] = True if correct_answers == given_answers else False
            elif 'txt' in question_answers:
                correct_answers = Question.objects.get(pk=question_pk).choices.filter(correct=True).first().body
                question_answers['correct'] = True if correct_answers == question_answers['txt'] else False
        return round(100 * sum(1 for elem in answers.values() if elem['correct']) / len(answers))


class ResultDetailsView(generic.DetailView):
    template_name = 'quiz/result_details.html'
    context_object_name = 'taken_quiz'
    model = TakenQuiz

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        answers_data = self.object.answers
        if answers_data:
            answers = loads(answers_data)
            questions = Question.objects.filter(pk__in=answers.keys())
            context['questions'] = []
            for question in questions:
                q_answers = answers[str(question.id)]
                if 'pk' in q_answers:
                    prepared_answers = [Choice.objects.get(pk=q_answers['pk'])]
                elif 'pks' in q_answers:
                    prepared_answers = list(Choice.objects.filter(pk__in=q_answers['pks']))
                elif 'txt' in q_answers:
                    prepared_answers = [{'body': q_answers['txt']}]
                context['questions'].append({
                    'object': question,
                    'answers': prepared_answers,
                    'correct': q_answers['correct']
                })
        else:
            context['questions'] = None
        return context


class UserResultsView(generic.ListView):
    template_name = 'quiz/taken_quizzes.html'
    context_object_name = 'taken_quizzes'

    def get_queryset(self):
        return self.request.user.taken_quizzes.exclude(score=None)


@method_decorator(moderator_required, name='dispatch')
class CategoryListView(generic.ListView):
    model = Category
    ordering = ('name', 'created_on')
    context_object_name = 'categories'
    template_name = 'quiz/category/category_change_list.html'

    def get_queryset(self):
        return self.request.user.created_categories\
            .annotate(quizzes_count=Count('quizzes', distinct=True))


@method_decorator(moderator_required, name='dispatch')
class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'quiz/category/category_add.html'
    fields = ('name', 'description')

    def form_valid(self, form):
        category = form.save(commit=False)
        category.creator = self.request.user
        category.save()
        messages.success(self.request, 'Категория успешно добавлена!')
        return redirect('quiz:category_change', category.pk)


@method_decorator(moderator_required, name='dispatch')
class CategoryUpdateView(generic.UpdateView):
    model = Category
    context_object_name = 'category'
    template_name = 'quiz/category/category_change.html'
    fields = ('name', 'description')

    def get_queryset(self):
        return self.request.user.created_categories.all()

    def get_success_url(self):
        return reverse('quiz:quiz_change', kwargs={'pk': self.object.pk})


@method_decorator(moderator_required, name='dispatch')
class CategoryDeleteView(generic.DeleteView):
    model = Category
    context_object_name = 'category'
    template_name = 'quiz/category/category_delete_confirmation.html'
    success_url = reverse_lazy('quiz:quiz_change_list')

    def delete(self, request, *args, **kwargs):
        category = self.get_object()
        if category.quizzes.exists():
            messages.error(request, 'Вы не можете удалить непустую категорию %s!' % category.name)
            return redirect('quiz:quiz_change_list')
        messages.success(request, 'Категория %s успешно удалена!' % category.name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.created_categories.all()

templates/quiz/quiz/question_add.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:quiz_change_list' %}">Мои опросники</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quiz:quiz_change' quiz.pk %}">{{ quiz.subject }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Добавить вопрос</li>
  </ol>
</nav>
<h2 class="mb-3">Добавление нового вопроса</h2>
<div class="col-md-6 col-sm-8 col-12">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-success">Сохранить</button>
    <a href="{% url 'quiz:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">Я передумал</a>
  </form>
</div>
{% endblock %}

templates/quiz/quiz/question_change.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:quiz_change_list' %}">Мои опросники</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quiz:quiz_change' quiz.pk %}">{{ quiz.subject }}</a></li>
    <li class="breadcrumb-item active">{{ question.subject }}</li>
  </ol>
</nav>
<form method="post">
  {% csrf_token %}
  {{ formset.management_form }}
  <div class="col-md-6 col-sm-8 col-12">
    {% bootstrap_form form %}
  </div>
  <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
    <div class="card-header">
      <div class="row">
        <div class="col">
          <strong>Варианты ответов</strong>
        </div>
        <div class=" text-right col">
          <strong>Ответ правильный?</strong>
        </div>
        <div class=" text-center col">
          <strong>Удалить из базы?</strong>
        </div>
      </div>
    </div>
    {% for error in formset.non_form_errors %}
      <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
    {% endfor %}
    <div class="list-group list-group-flush list-group-formset">
     {% for form in formset %}
       <div class="list-group-item">
         <div class="row">
           {% bootstrap_form form form_group_class='col' show_label=False %}
         </div>
       </div>
      {% endfor %}
    </div>
  </div>
  <p>
    <small class="form-text text-muted">У вопроса должно быть минимум <strong>2</strong> ответа и максимум <strong>10</strong>. Как минимум один из них верный.</small>
  </p>
  <button type="submit" class="btn btn-success">Сохранить</button>
  <a href="{% url 'quiz:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">Ничего не менять</a>
  <a href="{% url 'quiz:question_delete' quiz.pk question.pk %}" class="btn btn-danger float-right">Удалить вопрос</a>
</form>
{% endblock %}

templates/quiz/quiz/question_delete_confirmation.html
{% extends 'base.html' %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:quiz_change_list' %}">My Quizzes</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quiz:quiz_change' quiz.pk %}">{{ quiz.subject }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quiz:question_change' quiz.pk question.pk %}">{{ question.subject }}</a></li>
    <li class="breadcrumb-item active">Подтвердить удаление</li>
  </ol>
</nav>
<h2 class="mb-3">Удаление вопроса</h2>
<p class="lead">Вы уверены, что хотите удалить вопрос <strong>"{{ question.subject }}"</strong>?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger btn-lg">Да, удалить</button>
  <a href="{% url 'quiz:question_change' quiz.pk question.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Я передумал</a>
</form>
{% endblock %}

templates/quiz/quiz/quiz_add.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:quiz_change_list' %}">Мои опросы</a></li>
    <li class="breadcrumb-item active">Добавить новый опрос</li>
  </ol>
</nav>
<h2 class="mb-3">Добавление опроса</h2>
<div class="row">
  <div class="col-md-6 col-sm-8 col-12">
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-success">Сохранить</button>
      <a href="{% url 'quiz:quiz_change_list' %}" class="btn btn-outline-secondary" role="button">Я передумал</a>
    </form>
  </div>
</div>
{% endblock %}

templates/quiz/quiz/quiz_change.html
{% extends 'base.html' %}
{%load bootstrap4 %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:quiz_change_list' %}">Мои опросники</a></li>
    <li class="breadcrumb-item active">{{ quiz.subject }}</li>
  </ol>
</nav>
<h2 class="mb-3">{{ quiz.subject }}</h2>
<div class="row mb-3">
  <div class="col-md-6 col-sm-8 col-12">
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-success">Сохранить изменения</button>
      <a href="{% url 'quiz:quiz_change_list' %}" class="btn btn-outline-secondary" role="button">Я передумал</a>
      <a href="{% url 'quiz:quiz_delete' quiz.pk %}" class="btn btn-danger float-right">Удалить опросник</a>
    </form>
  </div>
</div>
{% if questions %}
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Вопрос</th>
        <th>Ответов</th>
      </tr>
    </thead>
    <tbody>
      {% for question in questions %}
        <tr class="clickable" href="{% url 'quiz:question_change' quiz.pk question.pk %}">
          <td>{{ question.subject }}</td>
          <td>{{ question.answers_count }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<p class="h5">Вопросов нет.</p>
{% endif %}
<a href="{% url 'quiz:question_add' quiz.pk %}" class="btn btn-success">Добавить вопрос</a>
{% endblock %}

templates/quiz/quiz/quiz_change_list.html
{% extends 'base.html' %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">Мои опросники</li>
  </ol>
</nav>
<h2 class="mb-3">Мои опросники</h2>
<a href="{% url 'quiz:quiz_add' %}" class="btn btn-success my-3" role="button">Добавить опрос</a>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Опрос</th>
        <th>Вопросов</th>
        <th>Пройден раз</th>
      </tr>
    </thead>
    <tbody>
      {% for quiz in quizzes %}
        <tr class="clickable" href="{% url 'quiz:quiz_change' quiz.pk %}">
          <td>{{ quiz.subject }}</td>
          <td>{{ quiz.questions_count }}</td>
          <td>{{ quiz.taken_count }}</td>
        </tr>
      {% empty %}
        <tr>
          <td class="bg-light text-center" colspan="5">Пока нет никаких опросов. </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/quiz/quiz/quiz_delete_confirmation.html
{% extends 'base.html' %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:quiz_change_list' %}">Мои опросники</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quiz:quiz_change' quiz.pk %}">{{ quiz.subject }}</a></li>
    <li class="breadcrumb-item active">Подтвердить удаление</li>
  </ol>
</nav>
<h2 class="mb-3">Удаление опроса</h2>
<p class="lead">Вы уверены, что хотите удалить опрос <strong>"{{ quiz.subject }}"?</strong></p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger btn-lg">Да, удалить</button>
  <a href="{% url 'quiz:quiz_change' quiz.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Я передумал</a>
</form>
{% endblock %}