base_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),
    path('users/', include('users.urls')),
    path('', include('quiz.urls')),
]

quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category_quizzes'),
    path('quiz/<int:pk>/', views.QuizView.as_view(), name='quiz_details'),
    path('quiz/<int:pk>/take/', views.TakeQuizView.as_view(), name='take_quiz'),
    path('result/<int:pk>/', views.ResultDetailsView.as_view(), name='result_details'),
    path('results/', views.UserResultsView.as_view(), name='results'),

    path('quizzes/change/', views.QuizListView.as_view(), name='quiz_change_list'),
    path('quiz/add/', views.QuizCreateView.as_view(), name='quiz_add'),
    path('quiz/<int:pk>/change/', views.QuizUpdateView.as_view(), name='quiz_change'),
    path('quiz/<int:pk>/delete/', views.QuizDeleteView.as_view(), name='quiz_delete'),

    path('categories/change/', views.CategoryListView.as_view(), name='category_change_list'),
    path('category/add/', views.CategoryCreateView.as_view(), name='category_add'),
    path('category/<int:pk>/change/', views.CategoryUpdateView.as_view(), name='category_change'),
    path('category/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('quiz/<int:pk>/question/add/', views.QuestionAddView.as_view(), name='question_add'),
    path('quiz/<int:quiz_pk>/question/<int:question_pk>/', views.question_change, name='question_change'),
    path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', views.QuestionDeleteView.as_view(), name='question_delete')
]

quiz/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        unique=True
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='created_categories'
    )
    description = models.TextField(max_length=500)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('quiz:category_quizzes', args=[str(self.id)])


class Quiz(models.Model):
    creator = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='created_quizzes'
    )
    created_on = models.DateTimeField(auto_now_add=True)
    subject = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='quizzes'
    )

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse('quiz:quiz_details', args=[str(self.id)])


class Question(models.Model):
    subject = models.CharField(max_length=100)
    body = models.TextField(max_length=1000)
    explanation = models.TextField(
        max_length=500,
        blank=True
    )
    question_type = models.CharField(
        max_length=1,
        choices=(
            ('R', 'Radio Button'),
            ('C', 'Checkbox'),
            ('T', 'Text field')
        ),
        default='R'
    )
    created_on = models.DateTimeField(auto_now_add=True)
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name='questions'
    )

    def __str__(self):
        return self.subject


class Choice(models.Model):
    body = models.TextField(max_length=500)
    created_on = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name='choices',
        null=True
    )
    correct = models.NullBooleanField()

    def __str__(self):
        return self.body


class TakenQuiz(models.Model):
    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='taken_quizzes'
    )
    created_on = models.DateTimeField(auto_now_add=True)
    time = models.DurationField(null=True)
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name='taken_quizzes'
    )
    score = models.FloatField(null=True)
    answers = models.TextField(blank=True)

    def __str__(self):
        return '{} taken by {} at {}, score: {}'.format(self.quiz, self.creator, self.created_on, self.score)

    def get_absolute_url(self):
        return reverse('quiz:result_details', args=[str(self.id)])

quiz/forms.py
from django import forms
from . import models
from django.core.exceptions import ValidationError


class BaseTakeQuizForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.question = question
        self.fields['answer'].queryset = question.choices.order_by('body')


class TakeQuizRadioForm(BaseTakeQuizForm):
    answer = forms.ModelChoiceField(
        queryset=models.Choice.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None,
        label='Варианты ответов'
    )


class TakeQuizMultiForm(BaseTakeQuizForm):
    answer = forms.ModelMultipleChoiceField(
        queryset=models.Choice.objects.none(),
        widget=forms.CheckboxSelectMultiple(),
        required=True,
        label='Варианты ответов'
    )


class TakeQuizTextForm(BaseTakeQuizForm):
    answer = forms.CharField(label='Введите ответ', widget=forms.Textarea(attrs={'cols': 20, 'rows': 2}))


class QuestionForm(forms.ModelForm):
    class Meta:
        model = models.Question
        fields = ('subject', 'body', 'explanation', 'question_type')


class BaseChoiceInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()
        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Отметьте хотя бы один верный ответ.', code='no_correct_answer')

quiz/views.py
from django.views import generic
from .models import Category, Quiz, Question, TakenQuiz, Choice
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.db.models import QuerySet, Count
from . import forms
from json import dumps, loads
from django.contrib import messages
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from users.decorators import moderator_required
from django.utils.decorators import method_decorator
from django.utils import timezone


class HomeView(generic.ListView):
    template_name = 'quiz/home.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.annotate(quizzes_count=Count('quizzes'))


class CategoryView(generic.ListView):
    template_name = 'quiz/category.html'
    context_object_name = 'quizzes'

    def get_category(self):
        return get_object_or_404(Category, pk=self.kwargs['pk'])

    def get_queryset(self):
        return self.get_category().quizzes.annotate(questions_count=Count('questions'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.get_category()
        return context


class QuizView(generic.DetailView):
    template_name = 'quiz/quiz.html'
    context_object_name = 'quiz'

    def get_queryset(self):
        return Quiz.objects.select_related('creator', 'category')\
            .filter(pk=self.kwargs['pk'])\
            .annotate(questions_count=Count('questions'))


class TakeQuizView(generic.FormView):
    template_name = 'quiz/take_quiz.html'
    http_method_names = ['post']

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        form = context_data['form']
        context_data.update({
            'question_num': self.request.session['quiz_data']['current_pos'] + 1,
            'questions_count': self.request.session['quiz_data']['total_questions'],
            'question': form.question,
            'quiz': form.question.quiz,
            'category': form.question.quiz.category,
        })
        return context_data

    def post(self, request, *args, **kwargs):
        quiz_data = request.session.get('quiz_data')
        if quiz_data:
            if quiz_data['quiz'] != kwargs['pk']:
                messages.error(request, 'Вы еще не завершили этот опрос.')
                return redirect('quiz:quiz_details', quiz_data['quiz'])
            form = self.get_form(data=request.POST)
            if form.is_valid():
                return self.form_valid(form)
            return self.form_invalid(form)
        return self.first_form(request, kwargs)

    def first_form(self, request, kwargs):
        quiz = get_object_or_404(Quiz, pk=kwargs['pk'])
        questions = list(quiz.questions.values_list('id', flat=True))
        taken_quiz = TakenQuiz.objects.create(
            creator=request.user,
            quiz=quiz
        )
        request.session['quiz_data'] = {
            'quiz': kwargs['pk'],
            'questions': questions,
            'current_pos': 0,
            'answers': {},
            'taken_quiz': taken_quiz.id,
            'total_questions': len(questions)
        }
        return self.render_to_response(self.get_context_data())

    def get_form(self, **kwargs):
        quiz_data = self.request.session['quiz_data']
        question = Question.objects \
            .select_related('quiz', 'quiz__category')\
            .get(pk=quiz_data['questions'][quiz_data['current_pos']])
        return {
            'R': forms.TakeQuizRadioForm,
            'C': forms.TakeQuizMultiForm,
            'T': forms.TakeQuizTextForm
        }[question.question_type](question, **kwargs)

    def form_valid(self, form):
        quiz_data = self.request.session['quiz_data']
        questions = quiz_data['questions']
        current_pos = quiz_data['current_pos']
        answer = form.cleaned_data['answer']
        if isinstance(answer, Choice):
            quiz_data['answers'][questions[current_pos]] = {'pk': form.cleaned_data['answer'].id}
        elif isinstance(answer, QuerySet):
            quiz_data['answers'][questions[current_pos]] = {'pks': list(form.cleaned_data['answer'].values_list('id', flat=True))}
        else:
            quiz_data['answers'][questions[current_pos]] = {'txt': form.cleaned_data['answer']}
        self.request.session['quiz_data']['answers'] = quiz_data['answers']
        if current_pos >= len(questions) - 1:
            score = self.calculate_results(quiz_data['answers'])
            taken_quiz = TakenQuiz.objects.select_related('quiz', 'quiz__category')\
                .get(id=quiz_data['taken_quiz'])
            taken_quiz.answers = dumps(quiz_data['answers'])
            taken_quiz.time = timezone.now() - taken_quiz.created_on
            taken_quiz.score = int(score)
            taken_quiz.save()
            del self.request.session['quiz_data']
            return render(self.request, 'quiz/finished_quiz.html', {
                'taken_quiz': taken_quiz,
                'category': taken_quiz.quiz.category,
                'quiz': taken_quiz.quiz
            })
        else:
            current_pos += 1
            quiz_data['current_pos'] = current_pos
            self.request.session['quiz_data'] = quiz_data
            return self.render_to_response(self.get_context_data())

    @staticmethod
    def calculate_results(answers):
        for question_pk, question_answers in answers.items():
            if 'pk' in question_answers:
                question_answers['correct'] = True if Choice.objects.get(pk=question_answers['pk']).correct is True else False
            elif 'pks' in question_answers:
                correct_answers = set(Question.objects.get(pk=question_pk).choices.filter(correct=True).values_list('id', flat=True))
                given_answers = set(question_answers['pks'])
                question_answers['correct'] = True if correct_answers == given_answers else False
            elif 'txt' in question_answers:
                correct_answers = Question.objects.get(pk=question_pk).choices.filter(correct=True).first().body
                question_answers['correct'] = True if correct_answers == question_answers['txt'] else False
        return round(100 * sum(1 for elem in answers.values() if elem['correct']) / len(answers))


class ResultDetailsView(generic.DetailView):
    template_name = 'quiz/result_details.html'
    context_object_name = 'taken_quiz'
    model = TakenQuiz

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        answers_data = self.object.answers
        if answers_data:
            answers = loads(answers_data)
            questions = Question.objects.filter(pk__in=answers.keys())
            context['questions'] = []
            for question in questions:
                q_answers = answers[str(question.id)]
                if 'pk' in q_answers:
                    prepared_answers = [Choice.objects.get(pk=q_answers['pk'])]
                elif 'pks' in q_answers:
                    prepared_answers = list(Choice.objects.filter(pk__in=q_answers['pks']))
                elif 'txt' in q_answers:
                    prepared_answers = [{'body': q_answers['txt']}]
                context['questions'].append({
                    'object': question,
                    'answers': prepared_answers,
                    'correct': q_answers['correct']
                })
        else:
            context['questions'] = None
        return context


class UserResultsView(generic.ListView):
    template_name = 'quiz/taken_quizzes.html'
    context_object_name = 'taken_quizzes'

    def get_queryset(self):
        return self.request.user.taken_quizzes.exclude(score=None)


@method_decorator(moderator_required, name='dispatch')
class CategoryListView(generic.ListView):
    model = Category
    ordering = ('name', 'created_on')
    context_object_name = 'categories'
    template_name = 'quiz/category/category_change_list.html'

    def get_queryset(self):
        return self.request.user.created_categories\
            .annotate(quizzes_count=Count('quizzes', distinct=True))


@method_decorator(moderator_required, name='dispatch')
class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'quiz/category/category_add.html'
    fields = ('name', 'description')

    def form_valid(self, form):
        category = form.save(commit=False)
        category.creator = self.request.user
        category.save()
        messages.success(self.request, 'Категория успешно добавлена!')
        return redirect('quiz:category_change', category.pk)


@method_decorator(moderator_required, name='dispatch')
class CategoryUpdateView(generic.UpdateView):
    model = Category
    context_object_name = 'category'
    template_name = 'quiz/category/category_change.html'
    fields = ('name', 'description')

    def get_queryset(self):
        return self.request.user.created_categories.all()

    def get_success_url(self):
        return reverse('quiz:quiz_change', kwargs={'pk': self.object.pk})


@method_decorator(moderator_required, name='dispatch')
class CategoryDeleteView(generic.DeleteView):
    model = Category
    context_object_name = 'category'
    template_name = 'quiz/category/category_delete_confirmation.html'
    success_url = reverse_lazy('quiz:quiz_change_list')

    def delete(self, request, *args, **kwargs):
        category = self.get_object()
        if category.quizzes.exists():
            messages.error(request, 'Вы не можете удалить непустую категорию %s!' % category.name)
            return redirect('quiz:quiz_change_list')
        messages.success(request, 'Категория %s успешно удалена!' % category.name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.created_categories.all()

templates/quiz/category.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:home' %}">Все категории</a></li>
    <li class="breadcrumb-item active">{{ category.name }}</li>
  </ol>
</nav>
<h1>{{ category.name }}</h1>
<p class="mt-4">{{ category.description }}</p>
{% if quizzes %}
<div class="table-responsive">
  <table class="table mt-5">
    <thead>
      <tr>
        <th>№</th>
        <th>Тема</th>
        <th>Количество вопросов</th>
        <th>Дата создания</th>
      </tr>
    </thead>
    <tbody>
    {% for quiz in quizzes %}
      <tr class="clickable" href="{% url 'quiz:quiz_details' quiz.pk %}">
        <td>{{ forloop.counter }}</td>
        <td>{{ quiz.subject }}</td>
        <td>{{ quiz.questions_count }}</td>
        <td>{{ quiz.created_on|naturaltime}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<div>Опросов в этой категории не найдено. </div>
{% endif %}
{% endblock %}

templates/quiz/finished_quiz.html
{% extends 'base.html' %}
{% block content %}
 <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:home' %}">Все категории</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quiz:category_quizzes' category.pk %}">{{ category.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quiz:quiz_details' quiz.pk %}">{{ quiz.subject }}</a></li>
  </ol>
</nav>
<h1>Ваш бал за прохождение опроса: {{ taken_quiz.score }}</h1>
<p class="mt-5">
Подробный отчет можно просмотреть <a class="btn btn-lg btn-success" href="{% url 'quiz:result_details' taken_quiz.pk %}">Тут</a>
</p>
{% endblock %}

templates/quiz/home.html
{% extends 'base.html' %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">Все категории</li>
  </ol>
</nav>
{% if categories %}
<div class="d-flex align-content-start flex-wrap">
  {% for category in categories %}
  <div class="m-2">
    <div class="card category clickable" href="{% url 'quiz:category_quizzes' category.pk %}">
      <div class="card-body" >
        <h2 class="card-title">{{ category.name }}</h2>
        <p class="card-text">{{ category.description }}</p>
        <a class="btn btn-outline-success mt-2" href="{% url 'quiz:category_quizzes' category.pk %}">
            Опросов <span class="badge badge-success">{{ category.quizzes_count }}</span>
        </a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<div>Пока нет никаких категорий.</div>
{% endif %}
{% endblock %}

templates/quiz/quiz.html
{% extends 'base.html' %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:home' %}">Все категории</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quiz:category_quizzes' quiz.category.pk %}">{{ quiz.category.name }}</a></li>
    <li class="breadcrumb-item active">{{ quiz.subject }}</li>
  </ol>
</nav>
<h1>{{ quiz.subject }}</h1>
<p class="mt-3">{{ quiz.description }}</p>
<p class="mb-0">Создатель: {{ quiz.creator }}</p>
<p class="mt-0">Вопросов: {{ quiz.questions_count }}</p>
{% if quiz.questions_count > 0 %}
<form action="take/" method="post">
  {% csrf_token %}
  <input class="btn btn-success btn-lg mt-4" type="submit" value="Пройти опрос!">
</form>
{% else %}
<p class="h5"> В этом опросе нет вопросов!</p>
{%endif%}
{% endblock %}

templates/quiz/result_details.html
{% extends 'base.html' %}
{% load humanize %}
{% load tags %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:home' %}">Все категории</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quiz:results' %}">Пройденные опросы</a></li>
    <li class="breadcrumb-item active">Отчет</li>
  </ol>
</nav>
<h2>В опросе {{ taken_quiz.quiz.subject }} набрано {{ taken_quiz.score }}</h2>
<p> Пройден за {{ taken_quiz.time|to_mins }} мин. пользователем {{taken_quiz.creator}} (начат {{ taken_quiz.created_on }})</p>
{% if questions %}
  {% for question in questions %}
  <hr>
    <div class="container row">
      <div class="col-8">
        <h3>{{ forloop.counter }}. {{ question.object.subject }}</h3>
        <p class="lead">{{ question.object.body }}</p>
      </div>
      <div class="col-1 aligh-bottom">
        {% if not question.correct and question.object.explanation %}
        <button type="button" data-placement="top" class="btn btn-outline-success" data-toggle="popover" data-content="{{ question.object.explanation }}">
        Подсказка
        </button>
        {% endif %}
      </div>
    </div>
    <div class="alert alert-{{ question.correct|yesno:"success,danger"}}">
    {% for answer in question.answers %}
      <p class="mb-0">{{ answer.body }}</p>
    {% endfor %}
    </div>
  {% endfor %}
{% else %}
<h3 class="mt-5">Вы не оставили ответов.</h3>
{% endif %}
{% endblock %}

templates/quiz/take_quiz.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:home' %}">Все категории</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quiz:category_quizzes' category.pk %}">{{ category.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quiz:quiz_details' quiz.pk %}">{{ quiz.subject }}</a></li>
  </ol>
</nav>
<p class="text-right"> Вопрос <span class="h3">{{ question_num }}/{{ questions_count }}</span></p>
<h3>{{ question.subject }}</h3>
<p class="my-3">{{ question.body}}</p>
<form class="form" action="" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary" type="submit" value="Далее" />
</form>
{% endblock %}

templates/quiz/taken_quizzes.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quiz:home' %}">Все категории</a></li>
    <li class="breadcrumb-item active">Пройденные опросы</li>
  </ol>
</nav>
{% if taken_quizzes %}
<h2>Пройденные опросы {{ request.user.username }}</h2>
<div class="table-responsive">
  <table class="table mt-5">
    <thead>
      <tr>
        <th>Опрос</th>
        <th>Очки</th>
        <th>Начат</th>
      </tr>
    </thead>
    <tbody>
    {% for taken_quiz in taken_quizzes %}
      <tr class="clickable" href="{% url 'quiz:result_details' taken_quiz.pk %}">
        <td>{{ taken_quiz.quiz.subject }}</td>
        <td>{{ taken_quiz.score }}</td>
        <td>{{ taken_quiz.created_on|naturaltime}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<div> Пройденных опросов не найдено. </div>
{% endif %}
{% endblock %}