base_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),
    path('users/', include('users.urls')),
    path('', include('quiz.urls')),
]

quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category_quizzes'),
    path('quiz/<int:pk>/', views.QuizView.as_view(), name='quiz_details'),
    path('quiz/<int:pk>/take/', views.TakeQuizView.as_view(), name='take_quiz'),
    path('result/<int:pk>/', views.ResultDetailsView.as_view(), name='result_details'),
    path('results/', views.UserResultsView.as_view(), name='results'),

    path('quizzes/change/', views.QuizListView.as_view(), name='quiz_change_list'),
    path('quiz/add/', views.QuizCreateView.as_view(), name='quiz_add'),
    path('quiz/<int:pk>/change/', views.QuizUpdateView.as_view(), name='quiz_change'),
    path('quiz/<int:pk>/delete/', views.QuizDeleteView.as_view(), name='quiz_delete'),

    path('categories/change/', views.CategoryListView.as_view(), name='category_change_list'),
    path('category/add/', views.CategoryCreateView.as_view(), name='category_add'),
    path('category/<int:pk>/change/', views.CategoryUpdateView.as_view(), name='category_change'),
    path('category/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('quiz/<int:pk>/question/add/', views.QuestionAddView.as_view(), name='question_add'),
    path('quiz/<int:quiz_pk>/question/<int:question_pk>/', views.question_change, name='question_change'),
    path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', views.QuestionDeleteView.as_view(), name='question_delete')
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.UsersWithReportsView.as_view(), name='users_with_reports'),
    path('<int:pk>/results/', views.UserResultsView.as_view(), name='user_results'),
    path('signup/', views.CustomSignupView.as_view(), name='signup'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('', include('django.contrib.auth.urls'))
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Quiz</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="icon" href="{% static 'icon.jpg' %}">
    <link rel="stylesheet" href="{% static 'css/base.css'%}">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-success">
      <a class="navbar-brand" href="/">Quiz</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'quiz:results' %}">Мои результаты</a>
          </li>
          {% if user|is_moderator %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Модерка
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'quiz:category_change_list' %}">Мои категории</a>
              <a class="dropdown-item" href="{% url 'quiz:quiz_change_list' %}">Мои опросники</a>
              <a class="dropdown-item" href="{% url 'users:users_with_reports' %}">Пользователи/Отчеты</a>
            </div>
          </li>
          {% endif %}
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="/admin/">Админка</a>
          </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Привет, {{ user.username }}!&nbsp&nbsp&nbsp<a class="btn btn-primary" href="{% url 'users:logout' %}">Выйти</a></span>
          </li>
          {% else %}
          <li class="nav-item">
            <span class="navbar-text">Вы не авторизованы.&nbsp&nbsp&nbsp<a class="btn btn-primary" href="{% url 'users:login' %}">Войти</a> или <a class="btn btn-primary" href="{% url 'users:signup' %}">Зарегистрироваться</a></span>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="card mb-3">
        <div class="card-body">
          {% for message in messages %}
          <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Закрыть">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/popover.js' %}"></script>
  </body>
</html>