base_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),
    path('users/', include('users.urls')),
    path('', include('quiz.urls')),
]

quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category_quizzes'),
    path('quiz/<int:pk>/', views.QuizView.as_view(), name='quiz_details'),
    path('quiz/<int:pk>/take/', views.TakeQuizView.as_view(), name='take_quiz'),
    path('result/<int:pk>/', views.ResultDetailsView.as_view(), name='result_details'),
    path('results/', views.UserResultsView.as_view(), name='results'),

    path('quizzes/change/', views.QuizListView.as_view(), name='quiz_change_list'),
    path('quiz/add/', views.QuizCreateView.as_view(), name='quiz_add'),
    path('quiz/<int:pk>/change/', views.QuizUpdateView.as_view(), name='quiz_change'),
    path('quiz/<int:pk>/delete/', views.QuizDeleteView.as_view(), name='quiz_delete'),

    path('categories/change/', views.CategoryListView.as_view(), name='category_change_list'),
    path('category/add/', views.CategoryCreateView.as_view(), name='category_add'),
    path('category/<int:pk>/change/', views.CategoryUpdateView.as_view(), name='category_change'),
    path('category/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('quiz/<int:pk>/question/add/', views.QuestionAddView.as_view(), name='question_add'),
    path('quiz/<int:quiz_pk>/question/<int:question_pk>/', views.question_change, name='question_change'),
    path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', views.QuestionDeleteView.as_view(), name='question_delete')
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.UsersWithReportsView.as_view(), name='users_with_reports'),
    path('<int:pk>/results/', views.UserResultsView.as_view(), name='user_results'),
    path('signup/', views.CustomSignupView.as_view(), name='signup'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('', include('django.contrib.auth.urls'))
]

users/views.py
from django.contrib.auth.views import LogoutView
from django.utils.decorators import method_decorator
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.shortcuts import redirect, get_object_or_404
from django.db.models import Count
from .decorators import moderator_required
from quiz.models import TakenQuiz


class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        unfinished_quizzes = TakenQuiz.objects.filter(creator=request.user, score=None)
        if unfinished_quizzes:
            unfinished_quizzes.update(score=0)
        return super().dispatch(request, *args, **kwargs)


class CustomSignupView(generic.CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('quiz:home')


@method_decorator(moderator_required, name='dispatch')
class UsersWithReportsView(generic.ListView):
    template_name = 'users/users_with_reports.html'
    context_object_name = 'users_with_reports'

    def get_queryset(self):
        return User.objects.exclude(taken_quizzes=None)\
            .annotate(taken_quizzes_count=Count('taken_quizzes'))


@method_decorator(moderator_required, name='dispatch')
class UserResultsView(generic.ListView):
    template_name = 'users/user_results.html'
    context_object_name = 'user_taken_quizzes'

    def get_queryset(self):
        return TakenQuiz.objects.filter(creator__id=self.kwargs['pk'])\
            .select_related('quiz')\
            .order_by('created_on')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['user'] = get_object_or_404(User, pk=self.kwargs['pk'])
        return context_data

templates/users/user_results.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'users:users_with_reports' %}">Все пользователи</a></li>
      <li class="breadcrumb-item active">{{ user.username }}</li>
  </ol>
</nav>
{% if user_taken_quizzes %}
<h2>Пройденные опросы {{ user.username }}</h2>
<div class="table-responsive">
  <table class="table mt-4">
    <thead>
      <tr>
        <th>Опрос</th>
        <th>Очки</th>
        <th>Начат</th>
      </tr>
    </thead>
    <tbody>
    {% for taken_quiz in user_taken_quizzes %}
      <tr class="clickable" href="{% url 'quiz:result_details' taken_quiz.pk %}">
        <td>{{ taken_quiz.quiz.subject }}</td>
        <td>{{ taken_quiz.score }}</td>
        <td>{{ taken_quiz.created_on|naturaltime}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<div> Пройденных опросов не найдено. </div>
{% endif %}
{% endblock %}

templates/users/users_with_reports.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">Все пользователи</li>
  </ol>
</nav>
<h2 class="mb-3">Пользователи с пройденными опросами</h2>
{% if users_with_reports %}
<div class="table-responsive">
  <table class="table my-4">
    <thead>
      <tr>
        <th>Пользователь</th>
        <th>Пройденных опросов</th>
        <th>Дата регистрации</th>
      </tr>
    </thead>
    <tbody>
    {% for user in users_with_reports %}
      <tr class="clickable" href="{% url 'users:user_results' user.pk %}">
        <td>{{ user.username }}</td>
        <td>{{ user.taken_quizzes_count }}</td>
        <td>{{ user.date_joined|naturaltime}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<p class="h4">Никто пока не проходил опросы. </p>
{% endif %}
{% endblock %}